export const flags = {
  Qatar: "🇶🇦",
  Ecuador: "🇪🇨",
  Senegal: "🇸🇳",
  Nederländerna: "🇳🇱",
  England: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
  Iran: "🇮🇷",
  USA: "🇺🇸",
  Wales: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
  Mexiko: "🇲🇽",
  Polen: "🇵🇱",
  Argentina: "🇦🇷",
  Saudiarabien: "🇸🇦",
  Frankrike: "🇫🇷",
  Australien: "🇦🇺",
  Danmark: "🇩🇰",
  Tunisien: "🇹🇳",
  Tyskland: "🇩🇪",
  Japan: "🇯🇵",
  Spanien: "🇪🇸",
  CostaRica: "🇨🇷",
  "Costa Rica": "🇨🇷",
  Belgien: "🇧🇪",
  Kanada: "🇨🇦",
  Marocko: "🇲🇦",
  Kroatien: "🇭🇷",
  Brasilien: "🇧🇷",
  Serbien: "🇷🇸",
  Schweiz: "🇨🇭",
  Kamerun: "🇨🇲",
  Portugal: "🇵🇹",
  Ghana: "🇬🇭",
  Uruguay: "🇺🇾",
  Sydkorea: "🇰🇷",
};
